-- MySQL Script generated by MySQL Workbench
-- 10/08/17 15:25:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET latin1 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`categoria` (
  `categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `usuario_baja` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`cliente` (
  `cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `nit` VARCHAR(20) NULL DEFAULT NULL,
  `empresa` VARCHAR(100) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0',
  `fecha_ingreso` DATETIME NULL DEFAULT NULL,
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `usuario_baja` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente`),
  UNIQUE INDEX `nit` (`nit` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`productos` (
  `producto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(9,4) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0',
  `categoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`producto`),
  INDEX `categoria` (`categoria` ASC),
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria`)
    REFERENCES `ventas`.`categoria` (`categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`tipo_documento` (
  `tipo_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_documento`),
  UNIQUE INDEX `nombre` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`roles` (
  `rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`usuario` (
  `usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `rol` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `username` (`username` ASC),
  INDEX `rol` (`rol` ASC),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`rol`)
    REFERENCES `ventas`.`roles` (`rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`venta` (
  `venta` INT(11) NOT NULL AUTO_INCREMENT,
  `corelativo` INT(11) UNSIGNED NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `subtotal` DECIMAL(9,4) NULL DEFAULT NULL,
  `igv` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_documento` INT(11) NULL DEFAULT NULL,
  `cliente` INT(11) NULL DEFAULT NULL,
  `usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`venta`),
  UNIQUE INDEX `corelativo` (`corelativo` ASC),
  INDEX `tipo_documento` (`tipo_documento` ASC),
  INDEX `cliente` (`cliente` ASC),
  INDEX `usuario` (`usuario` ASC),
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `ventas`.`tipo_documento` (`tipo_documento`),
  CONSTRAINT `venta_ibfk_2`
    FOREIGN KEY (`cliente`)
    REFERENCES `ventas`.`cliente` (`cliente`),
  CONSTRAINT `venta_ibfk_3`
    FOREIGN KEY (`usuario`)
    REFERENCES `ventas`.`usuario` (`usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas`.`detalle_venta` (
  `detalle_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` DECIMAL(9,4) NULL DEFAULT NULL,
  `importe` VARCHAR(45) NULL DEFAULT NULL,
  `producto` INT(11) NULL DEFAULT NULL,
  `venta` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`detalle_venta`),
  INDEX `producto` (`producto` ASC),
  INDEX `venta` (`venta` ASC),
  CONSTRAINT `detalle_venta_ibfk_1`
    FOREIGN KEY (`producto`)
    REFERENCES `ventas`.`productos` (`producto`),
  CONSTRAINT `detalle_venta_ibfk_2`
    FOREIGN KEY (`venta`)
    REFERENCES `ventas`.`venta` (`venta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
