-- MySQL Script generated by MySQL Workbench
-- dom 10 dic 2017 17:03:31 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas` DEFAULT CHARACTER SET latin1 ;
USE `ventas` ;

-- -----------------------------------------------------
-- Table `ventas`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`categoria` ;

CREATE TABLE IF NOT EXISTS `ventas`.`categoria` (
  `categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `estado` TINYINT(1) NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `usuario_baja` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`tipo_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`tipo_cliente` ;

CREATE TABLE IF NOT EXISTS `ventas`.`tipo_cliente` (
  `tipo_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `nombre` ON `ventas`.`tipo_cliente` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `ventas`.`tipo_documento` (
  `tipo_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_documento`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `nombre` ON `ventas`.`tipo_documento` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`cliente` ;

CREATE TABLE IF NOT EXISTS `ventas`.`cliente` (
  `cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_cliente` INT(11) NULL DEFAULT NULL,
  `tipo_documento` INT(11) NULL DEFAULT NULL,
  `num_documento` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0',
  `fecha_ingreso` DATETIME NULL DEFAULT NULL,
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `usuario_baja` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cliente`),
  CONSTRAINT `fk_cliente_1`
    FOREIGN KEY (`tipo_cliente`)
    REFERENCES `ventas`.`tipo_cliente` (`tipo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_2`
    FOREIGN KEY (`tipo_documento`)
    REFERENCES `ventas`.`tipo_documento` (`tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_cliente_1_idx` ON `ventas`.`cliente` (`tipo_cliente` ASC);

CREATE INDEX `fk_cliente_2_idx` ON `ventas`.`cliente` (`tipo_documento` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`productos` ;

CREATE TABLE IF NOT EXISTS `ventas`.`productos` (
  `producto` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `precio` DECIMAL(9,2) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '0',
  `categoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`producto`),
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categoria`)
    REFERENCES `ventas`.`categoria` (`categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `categoria` ON `ventas`.`productos` (`categoria` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`tipo_comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`tipo_comprobante` ;

CREATE TABLE IF NOT EXISTS `ventas`.`tipo_comprobante` (
  `tipo_comprobante` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `igv` INT(11) NULL DEFAULT NULL,
  `serie` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`tipo_comprobante`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`roles` ;

CREATE TABLE IF NOT EXISTS `ventas`.`roles` (
  `rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ventas`.`usuario` (
  `usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `rol` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`rol`)
    REFERENCES `ventas`.`roles` (`rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `email` ON `ventas`.`usuario` (`email` ASC);

CREATE UNIQUE INDEX `username` ON `ventas`.`usuario` (`username` ASC);

CREATE INDEX `rol` ON `ventas`.`usuario` (`rol` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`venta` ;

CREATE TABLE IF NOT EXISTS `ventas`.`venta` (
  `venta` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `subtotal` DECIMAL(9,4) NULL DEFAULT NULL,
  `igv` DECIMAL(10,0) NULL DEFAULT NULL,
  `descuento` DECIMAL(10,0) NULL DEFAULT NULL,
  `total` DECIMAL(10,0) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `num_documento` VARCHAR(45) NULL DEFAULT NULL,
  `usuario` INT(11) NULL DEFAULT NULL,
  `cliente` INT(11) NULL DEFAULT NULL,
  `tipo_comprobante` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`venta`),
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`tipo_comprobante`)
    REFERENCES `ventas`.`tipo_comprobante` (`tipo_comprobante`),
  CONSTRAINT `venta_ibfk_2`
    FOREIGN KEY (`cliente`)
    REFERENCES `ventas`.`cliente` (`cliente`),
  CONSTRAINT `venta_ibfk_3`
    FOREIGN KEY (`usuario`)
    REFERENCES `ventas`.`usuario` (`usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `cliente` ON `ventas`.`venta` (`cliente` ASC);

CREATE INDEX `usuario` ON `ventas`.`venta` (`usuario` ASC);

CREATE INDEX `venta_ibfk_1_idx` ON `ventas`.`venta` (`tipo_comprobante` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `ventas`.`detalle_venta` (
  `detalle_venta` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` DECIMAL(9,4) NULL DEFAULT NULL,
  `importe` VARCHAR(45) NULL DEFAULT NULL,
  `producto` INT(11) NULL DEFAULT NULL,
  `venta` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`detalle_venta`),
  CONSTRAINT `detalle_venta_ibfk_1`
    FOREIGN KEY (`producto`)
    REFERENCES `ventas`.`productos` (`producto`),
  CONSTRAINT `detalle_venta_ibfk_2`
    FOREIGN KEY (`venta`)
    REFERENCES `ventas`.`venta` (`venta`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `producto` ON `ventas`.`detalle_venta` (`producto` ASC);

CREATE INDEX `venta` ON `ventas`.`detalle_venta` (`venta` ASC);


-- -----------------------------------------------------
-- Table `ventas`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`menus` ;

CREATE TABLE IF NOT EXISTS `ventas`.`menus` (
  `menu` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `link` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`menu`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ventas`.`permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas`.`permisos` ;

CREATE TABLE IF NOT EXISTS `ventas`.`permisos` (
  `permiso` INT(11) NOT NULL AUTO_INCREMENT,
  `menu_id` INT(11) NULL DEFAULT NULL,
  `rol_id` INT(11) NULL DEFAULT NULL,
  `read` INT(11) NULL DEFAULT NULL,
  `insert` INT(11) NULL DEFAULT NULL,
  `update` INT(11) NULL DEFAULT NULL,
  `delete` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`permiso`),
  CONSTRAINT `fk_permisos_1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ventas`.`menus` (`menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permisos_2`
    FOREIGN KEY (`rol_id`)
    REFERENCES `ventas`.`roles` (`rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_permisos_1_idx` ON `ventas`.`permisos` (`menu_id` ASC);

CREATE INDEX `fk_permisos_2_idx` ON `ventas`.`permisos` (`rol_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
